//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetBucket.com.bd_ASP.NET_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Petsitter
    {
        public string id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string address { get; set; }
        public string nid { get; set; }
        public decimal balance { get; set; }
        public string phone { get; set; }
    }
}
